server:
  port: 9001

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1/bangbang?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  redis:
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: true
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000 # 连接超时时间（毫秒）
    max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
    max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    max-idle: 5 # 连接池中的最小空闲连接
    min-idle: 0 # 连接池中的最小空闲连接

mybatis-plus:
  mapper-locations：classpath:mappers/*xml